### ISSUE TITLE
Problems with the teleport to team member option when someone dies, and other changes request

### ISSUE THREAD

**Issue by vichocruz** [PauMAVA/UhcPlugin#12]
Hi PauMAVA! first of all, thank you very much for making this plugin, it's really amazing to have the possibility to play an UHC like the España one, and this is really similar to it. I wanted to share with you my experience and comparison between this and the plugin that is used in the original serie so maybe you could update it to be more similar.
First of all, the "Teleport to team member" option when a player dies seems to be broken, It didn't allow me to use it, just the other option (the one in the first slot of the hotbar).

Also I want to recommend you some other features that you could add to the code:
- Change the setMaxSize command to affect all the teams instead of team by team.
- Add an option to build the teams randomly with the people inside the server, set by the setMaxSize, f.e.: if there are 10 players connected to the server, and you set the setMaxSize to 2, it will form 5 teams of 2 randomly.
- You could also add the option of the UHC España T7 where it was an UHC of teams, but they started alone, and if the player was 100 blocks near of another player, he would see him with the glowing effect, and if he gets closer, and right clicked him, he would became his teammate and the team would have been created (this of course should be an option for enabling or disabling in the config file, because it overwrites the mechanic of making teams before the UHC starts).
- The golden apples crafted with the players heads should be named with the player's name, f.e.: ElRichMC's Golden Head, or something like that.
- For the crafting of the golden head it would be better to change it to 8 gold ingots instead of 4.
- You could also add the possibility of crafting a golden head of a wither skeleton skull.
- Please add the random mineral block under the fence that holds the player head when it dies (the original one uses 60% of block of gold, 20% emerald block and 20% iron, Lapis or Redstone block.
- You could add the option of the super golden apples and hyper golden apples (SGA gives instant health that cures 4 hearts and the HGA adds 2 filled heart containers) in UHC España the maximum amount of HGA that a player can eat is 15 (equivalent to 30 extra hearts).
- You could also add the custom crafting of the dragon's breath (with a strength potion and 8 gold nuggets).
- Give all the players a shulker box when the episode 8 starts.
- Give the players a complete new bar of hearts at the beginning of episode 10 or something like that (it could have the option the select at the beggining of what episode it gives it, and the option of enabling this or disabling. Same for the previous request of the shulker box).
- Change the drops of the Ghasts so they drop gold ingots instead of ghast tears.
- Hitting an opponent reveals his identity (in the case that you random change the names and skins of the players).
- /emergency to freeze the game in case of an emergency.
- Increase the probability of the drowned with trident to drop it, or add the possibility of drowned without trident to drop one; or both.
- Add a /afk or something like that, so when the player uses it is inmortal (in case that he goes afk and a creeper explodes him).
- Add a command like "/uhc teams rename" so the players can rename their own teams.

I really hope you could add this features as this would make this plugin to be almost exactly as the UHC España one. Thank you very much for writing this code, it has been extremely joyful for my and my friends to play, and I hope it will be getting better with the updates you are making.

**Comment by PauMAVA** [comment]
Hello @vichocruz ! 

First of all, I'm glad you are having good times using this plugin 😄 

I disabled the spectator teleport menu in order to prevent players from giving info about other teams to their teammates. But don't worry, I will add an option to the config in the next update so that it can be enabled and disabled.

I will do my best to start adding all the features you are suggesting. You can track this issue, where I will be posting a checklist and updating it every time I complete some features. 

Also, think that there are lots of features to implement so it can pass some months before they get all implemented. 

I'm also working on a skin rotation update (only for online mode) that I will release when I finish fixing some bugs. Probably I will add some of your feature requests to that update.

Thank you for requesting these features.

**Comment by PauMAVA** [comment]
**TODO LIST:**
- [x] Change the setMaxSize command to affect all the teams.

- [ ] Add an option to build the teams randomly with the people inside the server, set by the setMaxSize.

- [ ] Team creation by player proximity.

- [ ] Golden apples crafted with player heads should have the head's owner name as the item title.
  
- [ ] Add config option that defines the number of gold ingots needed to craft a golden apple with a player head.

- [ ] Crafting golden apples with wither skulls.
  
- [ ] Mineral block below player's death totem. (60% gold, 20% emerald, 20% iron or Lapis or Redstone).

- [x] Add Super Golden Apples (SGA) and Hyper Golden Apples (HGA). SGA fills 4 hearts and HGA adds 2 heart containers. (Limited to 15 per player).
  
- [ ] Add Dragon's Breath recipe.

- [x] Give shulkerbox to all players on an episode defined in the config.
 
- [ ] Add config option that adds a bar of health to all players on a predefined episode.

- [x] Change Ghast drops. It can be configured on the config file.
  
- [ ] Reveal the identity of an opponent on damaging it. 

- [ ] Add command to freeze the game. 
 
- [x] Increase the probability of drowned dropping a trident.

- [ ] Add config option for drowned drop probabilities.

- [ ] Add an AFK utility to prevent AFK deaths.

- [ ] Add a rename option for command /uhc teams

**Comment by vichocruz** [comment]
Hi PauMAVA!
I’m really glad you liked the things that I proposed you, and I think all
the other players that use your plugin will be thankfull too.
I’m writting you just because I think one of the points in your to-do-list
is wrong: the one about the SGA and HGA. You put that the HGA fills 40HP.
The thing is it should add two heart containers to the maximun health (if a
player eats it, for example, at the beggining of a match, he will now have
12 full hearts) so it increases the max health, and cures two hearts (so
the teo heart containers that gives are filled, I’m not sure if I’m
explaining myself well enough, sorry if not, my mother language is spanish
hahaha).
So both new golden apples are good, the SGA cures 4 complete hearts instead
of two like the HGA, but that one gives you two permanent heart containers.
Once again, thank you very much for taking the time to add this things, and
for considering my requests. I’ll be following this github to be up to date
with this plugin.

EDIT: I was thinking during the day, and I realized that maybe this could be also personalized in the config file. I don't know if it's possible, and if you agree, It's just something that I was thinking

Best regards!

**Comment by PauMAVA** [comment]
¿Por qué no hablamos en español? xD

Ahora cambio lo que me has dicho. 😄

**Comment by vichocruz** [comment]
JAJAJAJ haber sabido antes! Soy de Chile, hubiera sido más fácil explicar todo eso en español jajajaj pero que bueno que me hice entender igual. Bueno, nuevamente mil gracias por escuchar mis proposiciones y querer adicionarlas al código del plugin. Si hay algo en lo que pueda ayudarte dime, lamentablemente mis conocimientos de programación son prácticamente nulos, pero quedo a tu disposición ;)
Un abrazo!

**Comment by PauMAVA** [comment]
Como verás he añadido una issue para cada feature, de esta manera yo puedo tenerlo más ordenado y tu puedes ver el progreso sobre estos enchancements.

**Comment by vichocruz** [comment]
Se ve buenísimo todo! Acabo de revisarlos todos y me parece genial, si a ti te resulta mas ordenado, perfecto. Sobre todo lo de los teams in-game, que si no se crean, que en el episodio X se creen de manera random me pareció muy bueno.

**Comment by PauMAVA** [comment]
Como verás en la issue #30 hay que rehacer parte del plugin, lo que me va a llevar un tiempo. Aún así espero tener la release para Junio. 😄

**Comment by vichocruz** [comment]
Genial!! De verdad me encantaría poder ayudarte con ese código, pero como te comenté lamentablemente no tengo idea de programación :/ pero lo que sí puedo decirte es que, testeando me di cuenta de que, a pesar de que no esta permitida la opción de teleport to team member (esta como gris y no deja utilizarla), si deja usar la opción de teleport to other players, y ahí también aparecen los demás integrantes del team, por lo que mal que mal, no es algo que esté imposibilitado, sino que solo es un poco mas largo el proceso.
